/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendario;

import presentacion.FrmMain;

/**
 *
 * @author Alejandro Galindo
 */
public class PnlDiaCalendar extends javax.swing.JPanel {

    private FrmMain parent;
    
    private int dia;
    
    /**
     * Creates new form PnlDiaCalendar
     */
    public PnlDiaCalendar(FrmMain parentm, int dia) {
        initComponents();
        this.setSize(140, 70);
        this.parent = parent;
        this.dia = dia;
        this.textNum.setText(""+dia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNum = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        textNum.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
        textNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textNum.setText("31");
        textNum.setMaximumSize(new java.awt.Dimension(50, 50));
        textNum.setMinimumSize(new java.awt.Dimension(50, 50));
        textNum.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(textNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        DlgDiaCalendario ddc = new DlgDiaCalendario(parent, true, dia);
        ddc.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textNum;
    // End of variables declaration//GEN-END:variables
}
