/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.Cliente;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import negocio.INegocio;
import presentacion.utils.TextPrompt;

/**
 *
 * @author Alejandro Galindo
 */
public class DlgClientes extends javax.swing.JDialog {

    private INegocio fachada;

    private Cliente cliente;

    private Modals modal;

    /**
     * Creates new form DlgClientes
     */
    public DlgClientes(java.awt.Frame parent, boolean modal, Modals mode, Cliente cliente, INegocio fachada) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);

        this.fachada = fachada;
        this.cliente = cliente;
        this.modal = mode;

        if (mode == Modals.AGREGAR) {
            txtModal.setText("AGREGAR CLIENTE");
            btnModal.setText("AGREGAR");
            this.setTitle("AGREGAR CLIENTE");
            TextPrompt razon = new TextPrompt("NOMBRE DEL CLIENTE O RAZON SOCIAL", textRazon);
            razon.changeAlpha(0.75f);
            textRazon.setBorder(BorderFactory.createCompoundBorder(textRazon.getBorder(), BorderFactory.createEmptyBorder(10, 10, 10, 10)));
            
            TextPrompt rfc = new TextPrompt("REGISTRO FEDERAL DEL CONTRIBUYENTE (RFC)", textRFC);
            rfc.changeAlpha(0.75f);
            textRFC.setBorder(BorderFactory.createCompoundBorder(textRFC.getBorder(), BorderFactory.createEmptyBorder(10, 10, 10, 10)));
            
            TextPrompt telefono = new TextPrompt("TELEFONO", textTelefono);
            telefono.changeAlpha(0.75f);
            textTelefono.setBorder(BorderFactory.createCompoundBorder(textTelefono.getBorder(), BorderFactory.createEmptyBorder(10, 10, 10, 10)));
            
            TextPrompt correo = new TextPrompt("CORREO ELECTRÓNICO", textCorreo);
            correo.changeAlpha(0.75f);
            textCorreo.setBorder(BorderFactory.createCompoundBorder(textCorreo.getBorder(), BorderFactory.createEmptyBorder(10, 10, 10, 10)));
            
        } else if (mode == Modals.EDITAR) {
            txtModal.setText("EDITAR CLIENTE");
            btnModal.setText("EDITAR");
            this.setTitle("EDITAR CLIENTE");
            textRFC.setText(this.cliente.getRFC());
            textRazon.setText(this.cliente.getRazonSocial());
            textCorreo.setText(this.cliente.getCorreo());
            textTelefono.setText(this.cliente.getTelefono());
        }
    }

    private String validar() {
        String mensaje = "";
        if (textRFC.getText().equals("")) {
            mensaje = mensaje + "Asigne un RFC \n\r";
        }
        if (textRFC.getText().length() > 16) {
            mensaje = mensaje + "El RFC no puede ser mayor a 16 caracteres \n\r";
        }
        
        if (textRazon.getText().length() > 100) {
            mensaje = mensaje + "El Nombre o Razon social no puede ser mayor a 100 caracteres \n\r";
        }
        
        if(textRazon.getText().length() == 0 ) {
            mensaje = mensaje + "Ingrese un nombre o razon social \n\r";
        }
        
        if (textTelefono.getText().length() > 30) {
            mensaje = mensaje + "El Telefono no puede ser mayor a 30 caracteres \n\r";
        }
        
        if (textTelefono.getText().length() == 0) {
            mensaje = mensaje + "Ingrese un telefono \n\r";
        }
        
        if (textCorreo.getText().length() > 30) {
            mensaje = mensaje + "El Correo no puede ser mayor a 30 caracteres \n\r";
        }
        
        if (textCorreo.getText().length() == 0) {
            mensaje = mensaje + "Ingrese un Correo \n\r";
        }

        if (!textRFC.getText().matches("^[a-zA-Z]{3,4}(\\d{6})((\\D|\\d){2,3})?$")) {
            mensaje = mensaje + "RFC con formato incorrecto.\n\r CCC(C) AAMMDD XXX \n\r";
        }

        return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtModal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textRazon = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        textRFC = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnModal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtModal.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        txtModal.setText("MODALIDAD");

        textRazon.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        textRazon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textRazon.setMaximumSize(new java.awt.Dimension(59, 30));
        textRazon.setMinimumSize(new java.awt.Dimension(59, 30));
        textRazon.setName(""); // NOI18N
        textRazon.setPreferredSize(new java.awt.Dimension(59, 30));

        textTelefono.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        textTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textTelefono.setMaximumSize(new java.awt.Dimension(59, 30));
        textTelefono.setMinimumSize(new java.awt.Dimension(59, 30));
        textTelefono.setName(""); // NOI18N
        textTelefono.setPreferredSize(new java.awt.Dimension(59, 30));

        textCorreo.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        textCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textCorreo.setMaximumSize(new java.awt.Dimension(59, 30));
        textCorreo.setMinimumSize(new java.awt.Dimension(59, 30));
        textCorreo.setName(""); // NOI18N
        textCorreo.setPreferredSize(new java.awt.Dimension(59, 30));

        textRFC.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        textRFC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textRFC.setMaximumSize(new java.awt.Dimension(59, 30));
        textRFC.setMinimumSize(new java.awt.Dimension(59, 30));
        textRFC.setName(""); // NOI18N
        textRFC.setPreferredSize(new java.awt.Dimension(59, 30));

        btnCancelar.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModal.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        btnModal.setText("MODALIDAD");
        btnModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textRazon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtModal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textRFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 353, Short.MAX_VALUE)
                        .addComponent(btnModal)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtModal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModal, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas cancelar esta acción?", "Cancelar", JOptionPane.YES_NO_OPTION);

        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalActionPerformed
        String resultado = "";
        String validar = "";
        if (modal == Modals.AGREGAR) {
            validar = validar();
            if (validar.equals("")) {
                Cliente client = new Cliente(textRFC.getText(), textRazon.getText(), textCorreo.getText(), textTelefono.getText());
                resultado = fachada.agregarCliente(client);
            } else {
                resultado = validar;
            }
        } else if (modal == Modals.EDITAR) {
            validar = validar();

            if (validar.equals("")) {
                Cliente clientTemp = this.cliente;

                clientTemp.setRFC(textRFC.getText());
                clientTemp.setRazonSocial(textRazon.getText());
                clientTemp.setCorreo(textCorreo.getText());
                clientTemp.setTelefono(textTelefono.getText());

                resultado = fachada.editarCliente(clientTemp);
            } else {
                resultado = validar;
            }
        }
        JOptionPane.showMessageDialog(this, resultado, this.modal.toString(), JOptionPane.INFORMATION_MESSAGE);
        if(validar.equals("")){
            this.dispose();
        }
    }//GEN-LAST:event_btnModalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textRFC;
    private javax.swing.JTextField textRazon;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JLabel txtModal;
    // End of variables declaration//GEN-END:variables
}
